// ThreadDO execution tests — verifies the child DO pattern for parallel Python.
//
// ThreadDO.execute() creates a fresh WASM instance with:
//   - Minimal pymode imports (all return -1, no real bindings)
//   - Asyncify noop imports
//   - WASI with stdin/stdout for data flow
//
// We test the same execution pattern directly (can't instantiate a DO in tests)
// to prove stdin→Python→stdout works for the parallel spawn/join protocol.

import { describe, it, expect } from "vitest";
import pythonWasm from "../worker/src/python.wasm";
import { stdlibFS } from "../worker/src/stdlib-fs";
import { ProcExit, createWasi } from "../worker/src/wasi";

const encoder = new TextEncoder();
const decoder = new TextDecoder();

/**
 * Execute Python code with the same minimal imports ThreadDO uses.
 * This mirrors ThreadDO.execute() without the Durable Object wrapper.
 */
async function executeThread(
  code: string,
  stdinData?: Uint8Array
): Promise<{ stdout: Uint8Array; stderr: Uint8Array; exitCode: number }> {
  const files: Record<string, Uint8Array> = {};
  for (const [path, content] of Object.entries(stdlibFS)) {
    files[path] = encoder.encode(content);
  }

  let memory: WebAssembly.Memory | undefined;

  const args = ["python", "-S", "-c", code];
  const env = {
    PYTHONPATH: "/stdlib",
    PYTHONDONTWRITEBYTECODE: "1",
    PYTHONNOUSERSITE: "1",
  };

  const wasi = createWasi(args, env, files, () => memory!, stdinData);

  // Minimal pymode imports — same as ThreadDO
  const minimalPymode: Record<string, Function> = {
    tcp_connect: () => -1,
    tcp_send: () => -1,
    tcp_recv: () => -1,
    tcp_close: () => {},
    http_fetch_full: () => -1,
    kv_get: () => -1,
    kv_put: () => {},
    kv_delete: () => {},
    kv_multi_get: () => -1,
    kv_multi_put: () => {},
    r2_get: () => -1,
    r2_put: () => {},
    d1_exec: () => -1,
    d1_batch: () => -1,
    env_get: () => -1,
    thread_spawn: () => -1,
    thread_join: () => -1,
    dl_open: () => -1,
    dl_sym: () => 0,
    dl_close: () => {},
    dl_error: () => 0,
    console_log: () => {},
  };

  const asyncifyNoop: Record<string, Function> = {
    start_unwind: () => {},
    stop_unwind: () => {},
    start_rewind: () => {},
    stop_rewind: () => {},
  };

  try {
    const result = await WebAssembly.instantiate(pythonWasm, {
      wasi_snapshot_preview1: wasi.imports,
      pymode: minimalPymode,
      asyncify: asyncifyNoop,
    });
    const instance = (result as any).exports
      ? (result as WebAssembly.Instance)
      : (result as any).instance;
    memory = instance.exports.memory as WebAssembly.Memory;

    const start = instance.exports._start as () => void;
    start();

    return {
      stdout: wasi.getStdout(),
      stderr: wasi.getStderr(),
      exitCode: 0,
    };
  } catch (e: unknown) {
    if (e instanceof ProcExit) {
      return {
        stdout: wasi.getStdout(),
        stderr: wasi.getStderr(),
        exitCode: e.code,
      };
    }
    throw e;
  }
}

describe("ThreadDO execution pattern", () => {
  it("should run basic Python and capture stdout", async () => {
    const { stdout, exitCode } = await executeThread("print('thread-ok')");
    expect(exitCode).toBe(0);
    expect(decoder.decode(stdout).trim()).toBe("thread-ok");
  });

  it("should read stdin data", async () => {
    const input = encoder.encode("hello from parent");
    const { stdout, exitCode } = await executeThread(
      "import sys; data = sys.stdin.read(); print(f'got:{data}')",
      input
    );
    expect(exitCode).toBe(0);
    expect(decoder.decode(stdout).trim()).toBe("got:hello from parent");
  });

  it("should handle binary stdin/stdout (pickle protocol)", async () => {
    // Simulate the spawn/join protocol: pickle in → Python processes → pickle out
    // pickle.dumps({"a": 10, "b": 32}) generated by CPython 3.13
    const pickleInput = new Uint8Array([
      128, 4, 149, 17, 0, 0, 0, 0, 0, 0, 0, 125, 148, 40, 140, 1, 97, 148,
      75, 10, 140, 1, 98, 148, 75, 32, 117, 46,
    ]);

    const { stdout, exitCode } = await executeThread(`
import pickle, sys
input_data = sys.stdin.buffer.read()
task = pickle.loads(input_data)
result = task["a"] + task["b"]
output = pickle.dumps({"result": result})
sys.stdout.buffer.write(output)
`, pickleInput);

    expect(exitCode).toBe(0);
    // Verify we got valid pickle output (starts with pickle protocol marker)
    expect(stdout.length).toBeGreaterThan(0);
    expect(stdout[0]).toBe(0x80); // pickle protocol marker
  });

  it("should handle computation-heavy tasks", async () => {
    const { stdout, exitCode } = await executeThread(`
import sys
# Simulate a CPU-bound task a child DO might run
total = sum(i * i for i in range(10000))
print(total)
`);
    expect(exitCode).toBe(0);
    expect(decoder.decode(stdout).trim()).toBe("333283335000");
  });

  it("should capture stderr on errors", async () => {
    const { stderr, exitCode } = await executeThread(
      "raise ValueError('thread error')"
    );
    expect(exitCode).not.toBe(0);
    expect(decoder.decode(stderr)).toContain("ValueError: thread error");
  });

  it("should handle import errors gracefully", async () => {
    const { stderr, exitCode } = await executeThread(
      "import nonexistent_module_xyz"
    );
    expect(exitCode).not.toBe(0);
    expect(decoder.decode(stderr)).toContain("ModuleNotFoundError");
  });

  it("should isolate state between executions", async () => {
    // First execution sets a value
    const { stdout: out1, exitCode: code1 } = await executeThread(`
import sys
sys.modules['__test_marker'] = True
print('set')
`);
    expect(code1).toBe(0);
    expect(decoder.decode(out1).trim()).toBe("set");

    // Second execution should NOT see it (fresh WASM instance)
    const { stdout: out2, exitCode: code2 } = await executeThread(`
import sys
has_marker = hasattr(sys.modules.get('__test_marker', None), '__name__') if '__test_marker' in sys.modules else False
print(f'isolated:{not has_marker}')
`);
    expect(code2).toBe(0);
    expect(decoder.decode(out2).trim()).toBe("isolated:True");
  });

  it("should work with json serialization (alternative to pickle)", async () => {
    const input = encoder.encode(JSON.stringify({ items: [1, 2, 3, 4, 5] }));
    const { stdout, exitCode } = await executeThread(`
import json, sys
data = json.loads(sys.stdin.read())
result = {"sum": sum(data["items"]), "count": len(data["items"])}
print(json.dumps(result))
`, input);
    expect(exitCode).toBe(0);
    const result = JSON.parse(decoder.decode(stdout).trim());
    expect(result).toEqual({ sum: 15, count: 5 });
  });

  it("should handle empty stdin", async () => {
    const { stdout, exitCode } = await executeThread(
      "import sys; data = sys.stdin.read(); print(f'len:{len(data)}')"
    );
    expect(exitCode).toBe(0);
    expect(decoder.decode(stdout).trim()).toBe("len:0");
  });
});
