// Auto-generated by scripts/generate-stdlib-fs.py
// Loads stdlib data from a binary Data module (stdlib-data.dat).
// This keeps the JS script small while stdlib content is a separate asset.

// @ts-ignore — Data module import (ArrayBuffer), matched by wrangler rules
import stdlibData from "./stdlib-data.dat";

const _decoder = new TextDecoder();
export const stdlibFS: Record<string, string> = JSON.parse(
  _decoder.decode(stdlibData)
);
