// Auto-generated by scripts/generate-stdlib-fs.ts
// Loads stdlib data from a binary Data module (stdlib-data.dat) or, in
// production, from the ASSETS binding (deploy.js stubs the in-bundle copy
// and stages the real gzipped JSON at /_pymode/stdlib-data.dat.gz).

// @ts-ignore — Data module import (ArrayBuffer), matched by wrangler rules
import stdlibData from "./stdlib-data.dat";

async function _decompressBuf(buf: ArrayBuffer): Promise<string> {
  const stream = new Response(buf).body!.pipeThrough(
    new DecompressionStream("gzip"),
  );
  return await new Response(stream).text();
}

async function _decompressStream(resp: Response): Promise<string> {
  const stream = resp.body!.pipeThrough(new DecompressionStream("gzip"));
  return await new Response(stream).text();
}

let _cache: Record<string, string> | null = null;
let _pending: Promise<Record<string, string>> | null = null;

interface AssetsBinding {
  ASSETS?: { fetch: (req: Request) => Promise<Response> };
}

export function getStdlibFS(env?: AssetsBinding): Promise<Record<string, string>> {
  if (_cache) return Promise.resolve(_cache);
  if (!_pending) {
    _pending = (async () => {
      // Prefer the assets-hosted copy when available (production).
      if (env?.ASSETS) {
        try {
          const resp = await env.ASSETS.fetch(
            new Request("https://pymode.internal/_pymode/stdlib-data.dat.gz"),
          );
          const ct = resp.headers.get("content-type") || "";
          if (resp.ok && !ct.includes("text/html")) {
            const s = await _decompressStream(resp);
            if (s.length > 100) {
              _cache = JSON.parse(s);
              return _cache!;
            }
          }
        } catch {/* fall through to in-bundle */}
      }
      const s = await _decompressBuf(stdlibData);
      _cache = JSON.parse(s);
      return _cache!;
    })();
  }
  return _pending;
}
