import pythonWasm from "./python.wasm";
import { stdlibFS } from "./stdlib-fs.js";
import { DurableObject } from "cloudflare:workers";
import { connect } from "cloudflare:sockets";

// Optional: bundled third-party packages (generated by scripts/bundle-packages.py)
// When site-packages.zip exists, it's loaded as a Data module via wrangler rules.
let sitePackagesData: ArrayBuffer | undefined;
try {
  // @ts-ignore — conditional import, only present when zip is bundled
  sitePackagesData = require("./site-packages.zip");
} catch {
  // No site-packages bundled
}

interface TcpOp {
  op: "connect" | "send" | "recv" | "close";
  connId: string;
  host?: string;
  port?: number;
  dataBase64?: string;
  recvId?: number;
  bufsize?: number;
}

// TcpPoolDO: Holds persistent TCP connections across trampoline rounds.
// One instance per host:port pair. Connection persists in memory as long as the
// DO stays alive (70-140s idle timeout, extendable via alarm heartbeat).
// This eliminates the need to replay full TCP conversations each round.
export class TcpPoolDO extends DurableObject {
  private connections = new Map<string, {
    socket: any;
    reader: ReadableStreamDefaultReader<Uint8Array>;
    writer: WritableStreamDefaultWriter<Uint8Array>;
  }>();

  async tcpConnect(connId: string, host: string, port: number): Promise<void> {
    if (this.connections.has(connId)) return; // already connected
    const socket = connect({ hostname: host, port });
    const writer = socket.writable.getWriter();
    const reader = socket.readable.getReader();
    this.connections.set(connId, { socket, writer, reader });
  }

  async tcpSend(connId: string, dataBase64: string): Promise<void> {
    const conn = this.connections.get(connId);
    if (!conn) throw new Error(`send on unknown connection: ${connId}`);
    const binary = atob(dataBase64);
    const data = new Uint8Array(binary.length);
    for (let i = 0; i < binary.length; i++) data[i] = binary.charCodeAt(i);
    await conn.writer.write(data);
  }

  async tcpRecv(connId: string, bufsize: number): Promise<string> {
    const conn = this.connections.get(connId);
    if (!conn) throw new Error(`recv on unknown connection: ${connId}`);

    const timeoutPromise = new Promise<{ value: undefined; done: true }>((resolve) =>
      setTimeout(() => resolve({ value: undefined, done: true }), 10000)
    );

    const result = await Promise.race([conn.reader.read(), timeoutPromise]);
    if (result.done || !result.value) return "";

    const bytes = result.value.slice(0, bufsize);
    let binary = "";
    for (let i = 0; i < bytes.length; i++) binary += String.fromCharCode(bytes[i]);
    return btoa(binary);
  }

  async tcpClose(connId: string): Promise<void> {
    const conn = this.connections.get(connId);
    if (!conn) return;
    try { conn.writer.releaseLock(); } catch {}
    try { conn.reader.releaseLock(); } catch {}
    try { conn.socket.close(); } catch {}
    this.connections.delete(connId);
  }

  // Replay a full ops log in a single RPC session (1 billed request).
  // Returns a map of recvId → base64-encoded response data.
  async replayOps(ops: TcpOp[]): Promise<Record<number, string>> {
    const recvResults: Record<number, string> = {};

    for (const op of ops) {
      switch (op.op) {
        case "connect":
          await this.tcpConnect(op.connId, op.host!, op.port!);
          break;
        case "send":
          await this.tcpSend(op.connId, op.dataBase64!);
          break;
        case "recv": {
          const data = await this.tcpRecv(op.connId, op.bufsize || 65536);
          recvResults[op.recvId!] = data;
          break;
        }
        case "close":
          await this.tcpClose(op.connId);
          break;
      }
    }

    return recvResults;
  }
}

// Custom synchronous WASI shim for running Python on CF Workers.
// Unlike @cloudflare/workers-wasi, this doesn't need asyncify because
// all syscalls are backed by an in-memory filesystem with zero I/O.

interface Env {
  PYMODE_DATA?: KVNamespace;
  TCP_POOL?: DurableObjectNamespace;
}

class ProcExit extends Error {
  code: number;
  constructor(code: number) {
    super(`proc_exit(${code})`);
    this.code = code;
  }
}

interface WasiResult {
  exitCode: number;
  stdout: Uint8Array;
  stderr: Uint8Array;
  files: Record<string, Uint8Array>;
  writtenFiles: Map<string, Uint8Array>;
}

function createWasi(
  args: string[],
  env: Record<string, string>,
  files: Record<string, Uint8Array>,
  getMemory: () => WebAssembly.Memory
) {
  const encoder = new TextEncoder();
  const decoder = new TextDecoder();

  const FD_STDIN = 0;
  const FD_STDOUT = 1;
  const FD_STDERR = 2;
  const FD_PREOPEN = 3;       // /stdlib (read-only stdlib + pymode runtime)
  const FD_DATA_PREOPEN = 4;  // /data (read-write, backed by CF KV)

  const preopenPath = "/stdlib";
  const dataPreopenPath = "/data";

  interface OpenFile {
    path: string;
    data: Uint8Array;
    offset: number;
    isDir: boolean;
    writable: boolean;
  }

  const openFiles = new Map<number, OpenFile>();
  let nextFd = FD_DATA_PREOPEN + 1;

  const stdoutChunks: Uint8Array[] = [];
  const stderrChunks: Uint8Array[] = [];

  // Writable files layer — sits on top of the read-only files map
  const writtenFiles = new Map<string, Uint8Array>();

  // Build directory index from file paths
  const dirChildren = new Map<string, string[]>();
  dirChildren.set("", []);
  for (const path of Object.keys(files)) {
    const parts = path.split("/");
    for (let i = 0; i < parts.length - 1; i++) {
      const parent = parts.slice(0, i).join("/");
      const child = parts[i];
      if (!dirChildren.has(parent)) dirChildren.set(parent, []);
      const list = dirChildren.get(parent)!;
      if (!list.includes(child)) list.push(child);
      const full = parts.slice(0, i + 1).join("/");
      if (!dirChildren.has(full)) dirChildren.set(full, []);
    }
    const dir = parts.slice(0, -1).join("/");
    const name = parts[parts.length - 1];
    if (!dirChildren.has(dir)) dirChildren.set(dir, []);
    const list = dirChildren.get(dir)!;
    if (!list.includes(name)) list.push(name);
  }

  // Ensure /tmp directory exists for trampoline files
  if (!dirChildren.has("tmp")) {
    dirChildren.set("tmp", []);
    const root = dirChildren.get("")!;
    if (!root.includes("tmp")) root.push("tmp");
  }

  // Ensure /data directory exists for persistent storage
  if (!dirChildren.has("data")) {
    dirChildren.set("data", []);
    const root = dirChildren.get("")!;
    if (!root.includes("data")) root.push("data");
  }

  function isDir(path: string): boolean {
    return dirChildren.has(path);
  }

  function fileExists(path: string): boolean {
    return writtenFiles.has(path) || path in files;
  }

  function fileData(path: string): Uint8Array | undefined {
    return writtenFiles.get(path) || files[path];
  }

  // Register a directory in the VFS (creates parent chain)
  function ensureDir(path: string): void {
    if (dirChildren.has(path)) return;
    const parts = path.split("/");
    for (let i = 1; i <= parts.length; i++) {
      const dir = parts.slice(0, i).join("/");
      if (!dirChildren.has(dir)) {
        dirChildren.set(dir, []);
        const parent = parts.slice(0, i - 1).join("/");
        if (!dirChildren.has(parent)) dirChildren.set(parent, []);
        const parentList = dirChildren.get(parent)!;
        const name = parts[i - 1];
        if (!parentList.includes(name)) parentList.push(name);
      }
    }
  }

  // Register a file in its parent directory's children list
  function registerFile(path: string): void {
    const parts = path.split("/");
    const dir = parts.slice(0, -1).join("/");
    const name = parts[parts.length - 1];
    ensureDir(dir);
    const list = dirChildren.get(dir)!;
    if (!list.includes(name)) list.push(name);
  }

  function view(): DataView { return new DataView(getMemory().buffer); }
  function mem(): Uint8Array { return new Uint8Array(getMemory().buffer); }

  const ESUCCESS = 0;
  const EBADF = 8;
  const EEXIST = 20;
  const EINVAL = 28;
  const EISDIR = 31;
  const ENOENT = 44;
  const ENOSYS = 52;
  const ENOTDIR = 54;

  function normalizePath(p: string): string {
    let r = p.replace(/^\.\//, "").replace(/\/\.\//g, "/").replace(/\/+/g, "/").replace(/\/$/, "");
    if (r === ".") r = "";
    return r;
  }

  function resolvePath(dirFd: number, relPath: string): string | null {
    if (dirFd === FD_PREOPEN) return normalizePath(relPath);
    if (dirFd === FD_DATA_PREOPEN) return normalizePath("data/" + relPath);
    const dir = openFiles.get(dirFd);
    if (!dir) return null;
    if (dir.path === "") return normalizePath(relPath);
    return normalizePath(dir.path + "/" + relPath);
  }

  const imports = {
    args_get(argvPtr: number, bufPtr: number): number {
      const v = view();
      for (const arg of args) {
        v.setUint32(argvPtr, bufPtr, true);
        argvPtr += 4;
        const bytes = encoder.encode(arg + "\0");
        mem().set(bytes, bufPtr);
        bufPtr += bytes.length;
      }
      return ESUCCESS;
    },

    args_sizes_get(countPtr: number, sizePtr: number): number {
      const v = view();
      v.setUint32(countPtr, args.length, true);
      let size = 0;
      for (const arg of args) size += encoder.encode(arg + "\0").length;
      v.setUint32(sizePtr, size, true);
      return ESUCCESS;
    },

    environ_get(envPtr: number, bufPtr: number): number {
      const v = view();
      for (const [key, val] of Object.entries(env)) {
        v.setUint32(envPtr, bufPtr, true);
        envPtr += 4;
        const bytes = encoder.encode(`${key}=${val}\0`);
        mem().set(bytes, bufPtr);
        bufPtr += bytes.length;
      }
      return ESUCCESS;
    },

    environ_sizes_get(countPtr: number, sizePtr: number): number {
      const v = view();
      const entries = Object.entries(env);
      v.setUint32(countPtr, entries.length, true);
      let size = 0;
      for (const [key, val] of entries) size += encoder.encode(`${key}=${val}\0`).length;
      v.setUint32(sizePtr, size, true);
      return ESUCCESS;
    },

    clock_time_get(_id: number, _precision: bigint, retPtr: number): number {
      view().setBigUint64(retPtr, BigInt(Date.now()) * BigInt(1_000_000), true);
      return ESUCCESS;
    },

    clock_res_get(_id: number, retPtr: number): number {
      view().setBigUint64(retPtr, BigInt(1_000_000), true);
      return ESUCCESS;
    },

    fd_write(fd: number, iovsPtr: number, iovsLen: number, retPtr: number): number {
      const v = view();
      const m = mem();
      let written = 0;

      if (fd === FD_STDOUT || fd === FD_STDERR) {
        const chunks = fd === FD_STDOUT ? stdoutChunks : stderrChunks;
        for (let i = 0; i < iovsLen; i++) {
          const ptr = v.getUint32(iovsPtr + i * 8, true);
          const len = v.getUint32(iovsPtr + i * 8 + 4, true);
          chunks.push(m.slice(ptr, ptr + len));
          written += len;
        }
        v.setUint32(retPtr, written, true);
        return ESUCCESS;
      }

      const file = openFiles.get(fd);
      if (!file || !file.writable) return EBADF;

      // Gather all iov data
      for (let i = 0; i < iovsLen; i++) {
        const ptr = v.getUint32(iovsPtr + i * 8, true);
        const len = v.getUint32(iovsPtr + i * 8 + 4, true);
        const chunk = m.slice(ptr, ptr + len);

        // Grow buffer if needed
        const needed = file.offset + chunk.length;
        if (needed > file.data.length) {
          const grown = new Uint8Array(needed);
          grown.set(file.data);
          file.data = grown;
          writtenFiles.set(file.path, grown);
        }
        file.data.set(chunk, file.offset);
        file.offset += chunk.length;
        written += chunk.length;
      }

      v.setUint32(retPtr, written, true);
      return ESUCCESS;
    },

    fd_read(fd: number, iovsPtr: number, iovsLen: number, retPtr: number): number {
      const v = view();
      const m = mem();
      if (fd === FD_STDIN) {
        v.setUint32(retPtr, 0, true);
        return ESUCCESS;
      }
      const file = openFiles.get(fd);
      if (!file) return EBADF;
      let totalRead = 0;
      for (let i = 0; i < iovsLen; i++) {
        const ptr = v.getUint32(iovsPtr + i * 8, true);
        const len = v.getUint32(iovsPtr + i * 8 + 4, true);
        const remaining = file.data.length - file.offset;
        const toRead = Math.min(len, remaining);
        if (toRead > 0) {
          m.set(file.data.subarray(file.offset, file.offset + toRead), ptr);
          file.offset += toRead;
          totalRead += toRead;
        }
        if (toRead < len) break;
      }
      v.setUint32(retPtr, totalRead, true);
      return ESUCCESS;
    },

    fd_seek(fd: number, offset: bigint, whence: number, retPtr: number): number {
      const file = openFiles.get(fd);
      if (!file) return EBADF;
      const off = Number(offset);
      let newOffset: number;
      if (whence === 0) newOffset = off;
      else if (whence === 1) newOffset = file.offset + off;
      else if (whence === 2) newOffset = file.data.length + off;
      else return EINVAL;
      if (newOffset < 0) return EINVAL;
      file.offset = newOffset;
      view().setBigUint64(retPtr, BigInt(file.offset), true);
      return ESUCCESS;
    },

    fd_close(fd: number): number {
      if (fd <= FD_DATA_PREOPEN) return ESUCCESS;
      openFiles.delete(fd);
      return ESUCCESS;
    },

    fd_prestat_get(fd: number, retPtr: number): number {
      const preopens: Record<number, string> = {
        [FD_PREOPEN]: preopenPath,
        [FD_DATA_PREOPEN]: dataPreopenPath,
      };
      const path = preopens[fd];
      if (path !== undefined) {
        const v = view();
        v.setUint8(retPtr, 0); // PREOPENTYPE_DIR
        v.setUint32(retPtr + 4, encoder.encode(path).length, true);
        return ESUCCESS;
      }
      return EBADF;
    },

    fd_prestat_dir_name(fd: number, pathPtr: number, pathLen: number): number {
      const preopens: Record<number, string> = {
        [FD_PREOPEN]: preopenPath,
        [FD_DATA_PREOPEN]: dataPreopenPath,
      };
      const path = preopens[fd];
      if (path !== undefined) {
        mem().set(encoder.encode(path).subarray(0, pathLen), pathPtr);
        return ESUCCESS;
      }
      return EBADF;
    },

    fd_fdstat_get(fd: number, retPtr: number): number {
      const v = view();
      const m = new Uint8Array(getMemory().buffer);
      // Zero out the struct (24 bytes)
      m.fill(0, retPtr, retPtr + 24);
      if (fd <= FD_STDERR) {
        v.setUint8(retPtr, 2); // CHARACTER_DEVICE
        v.setBigUint64(retPtr + 8, BigInt(0x1FF), true);
        v.setBigUint64(retPtr + 16, BigInt(0x1FF), true);
        return ESUCCESS;
      }
      if (fd === FD_PREOPEN || fd === FD_DATA_PREOPEN) {
        v.setUint8(retPtr, 3); // DIRECTORY
        v.setBigUint64(retPtr + 8, BigInt(0x1FFFFFF), true);
        v.setBigUint64(retPtr + 16, BigInt(0x1FFFFFF), true);
        return ESUCCESS;
      }
      const file = openFiles.get(fd);
      if (!file) return EBADF;
      v.setUint8(retPtr, file.isDir ? 3 : 4);
      v.setBigUint64(retPtr + 8, BigInt(0x1FFFFFF), true);
      v.setBigUint64(retPtr + 16, BigInt(0x1FFFFFF), true);
      return ESUCCESS;
    },

    path_open(
      dirFd: number, _dirflags: number,
      pathPtr: number, pathLen: number,
      oflags: number, _fsRightsBase: bigint, _fsRightsInheriting: bigint,
      _fdflags: number, retPtr: number
    ): number {
      const pathStr = decoder.decode(mem().subarray(pathPtr, pathPtr + pathLen));
      const fullPath = resolvePath(dirFd, pathStr);
      if (fullPath === null) return EBADF;

      const OFLAGS_CREAT = 1;
      const OFLAGS_TRUNC = 8;

      // O_CREAT — create a new writable file (or open existing writable file)
      if (oflags & OFLAGS_CREAT) {
        const fd = nextFd++;
        if (!writtenFiles.has(fullPath) || (oflags & OFLAGS_TRUNC)) {
          writtenFiles.set(fullPath, new Uint8Array(0));
        }
        registerFile(fullPath);
        openFiles.set(fd, {
          path: fullPath,
          data: writtenFiles.get(fullPath)!,
          offset: 0,
          isDir: false,
          writable: true,
        });
        view().setUint32(retPtr, fd, true);
        return ESUCCESS;
      }

      // Check writable files first, then read-only files
      const data = fileData(fullPath);
      if (data) {
        const fd = nextFd++;
        const writable = writtenFiles.has(fullPath);
        openFiles.set(fd, { path: fullPath, data, offset: 0, isDir: false, writable });
        view().setUint32(retPtr, fd, true);
        return ESUCCESS;
      }
      if (isDir(fullPath)) {
        const fd = nextFd++;
        openFiles.set(fd, { path: fullPath, data: new Uint8Array(0), offset: 0, isDir: true, writable: false });
        view().setUint32(retPtr, fd, true);
        return ESUCCESS;
      }
      return ENOENT;
    },

    path_filestat_get(
      dirFd: number, _flags: number,
      pathPtr: number, pathLen: number, retPtr: number
    ): number {
      const pathStr = decoder.decode(mem().subarray(pathPtr, pathPtr + pathLen));
      const fullPath = resolvePath(dirFd, pathStr);
      if (fullPath === null) return EBADF;

      const data = fileData(fullPath);
      const isDirPath = isDir(fullPath);
      if (!data && !isDirPath) return ENOENT;

      const v = view();
      const m = new Uint8Array(getMemory().buffer);
      m.fill(0, retPtr, retPtr + 64);
      v.setUint8(retPtr + 16, isDirPath && !data ? 3 : 4);
      v.setBigUint64(retPtr + 24, BigInt(1), true);
      v.setBigUint64(retPtr + 32, BigInt(data ? data.length : 0), true);
      return ESUCCESS;
    },

    fd_filestat_get(fd: number, retPtr: number): number {
      const m = new Uint8Array(getMemory().buffer);
      const v = view();
      m.fill(0, retPtr, retPtr + 64);
      if (fd <= FD_STDERR) {
        v.setUint8(retPtr + 16, 2);
        v.setBigUint64(retPtr + 24, BigInt(1), true);
        return ESUCCESS;
      }
      if (fd === FD_PREOPEN || fd === FD_DATA_PREOPEN) {
        v.setUint8(retPtr + 16, 3);
        v.setBigUint64(retPtr + 24, BigInt(1), true);
        return ESUCCESS;
      }
      const file = openFiles.get(fd);
      if (!file) return EBADF;
      v.setUint8(retPtr + 16, file.isDir ? 3 : 4);
      v.setBigUint64(retPtr + 24, BigInt(1), true);
      v.setBigUint64(retPtr + 32, BigInt(file.data.length), true);
      return ESUCCESS;
    },

    fd_readdir(
      fd: number, bufPtr: number, bufLen: number,
      cookie: bigint, retPtr: number
    ): number {
      const file = openFiles.get(fd);
      if (!file && fd !== FD_PREOPEN && fd !== FD_DATA_PREOPEN) return EBADF;
      const dirPath = fd === FD_PREOPEN ? "" : fd === FD_DATA_PREOPEN ? "data" : file!.path;
      const entries = dirChildren.get(dirPath) || [];
      const v = view();
      const m = mem();

      let offset = 0;
      const startIdx = Number(cookie);
      for (let i = startIdx; i < entries.length; i++) {
        const name = entries[i];
        const nameBytes = encoder.encode(name);
        const entrySize = 24 + nameBytes.length;
        if (offset + entrySize > bufLen) break;

        const base = bufPtr + offset;
        v.setBigUint64(base, BigInt(i + 1), true);
        v.setBigUint64(base + 8, BigInt(0), true);
        v.setUint32(base + 16, nameBytes.length, true);
        const childPath = dirPath ? `${dirPath}/${name}` : name;
        v.setUint8(base + 20, isDir(childPath) ? 3 : 4);
        m.set(nameBytes, base + 24);
        offset += entrySize;
      }

      v.setUint32(retPtr, offset, true);
      return ESUCCESS;
    },

    fd_tell(fd: number, retPtr: number): number {
      const file = openFiles.get(fd);
      if (!file) return EBADF;
      view().setBigUint64(retPtr, BigInt(file.offset), true);
      return ESUCCESS;
    },

    fd_advise(): number { return ESUCCESS; },
    fd_allocate(): number { return ESUCCESS; },
    fd_datasync(): number { return ESUCCESS; },
    fd_sync(): number { return ESUCCESS; },
    fd_fdstat_set_flags(): number { return ESUCCESS; },
    fd_fdstat_set_rights(): number { return ESUCCESS; },
    fd_filestat_set_size(): number { return ESUCCESS; },
    fd_filestat_set_times(): number { return ESUCCESS; },
    fd_pread(): number { return ENOSYS; },
    fd_pwrite(): number { return ENOSYS; },
    fd_renumber(): number { return ENOSYS; },

    path_create_directory(dirFd: number, pathPtr: number, pathLen: number): number {
      const pathStr = decoder.decode(mem().subarray(pathPtr, pathPtr + pathLen));
      const fullPath = resolvePath(dirFd, pathStr);
      if (fullPath === null) return EBADF;
      if (dirChildren.has(fullPath)) return EEXIST;
      ensureDir(fullPath);
      return ESUCCESS;
    },

    path_filestat_set_times(): number { return ESUCCESS; },
    path_link(): number { return ENOSYS; },
    path_readlink(): number { return ENOSYS; },

    path_remove_directory(dirFd: number, pathPtr: number, pathLen: number): number {
      const pathStr = decoder.decode(mem().subarray(pathPtr, pathPtr + pathLen));
      const fullPath = resolvePath(dirFd, pathStr);
      if (fullPath === null) return EBADF;
      if (!dirChildren.has(fullPath)) return ENOENT;
      const children = dirChildren.get(fullPath)!;
      if (children.length > 0) return ENOENT; // ENOTEMPTY mapped to ENOENT
      dirChildren.delete(fullPath);
      // Remove from parent
      const parts = fullPath.split("/");
      const name = parts.pop()!;
      const parent = parts.join("/");
      const siblings = dirChildren.get(parent);
      if (siblings) {
        const idx = siblings.indexOf(name);
        if (idx !== -1) siblings.splice(idx, 1);
      }
      return ESUCCESS;
    },

    path_rename(
      oldDirFd: number, oldPathPtr: number, oldPathLen: number,
      newDirFd: number, newPathPtr: number, newPathLen: number
    ): number {
      const m = mem();
      const oldPathStr = decoder.decode(m.subarray(oldPathPtr, oldPathPtr + oldPathLen));
      const newPathStr = decoder.decode(m.subarray(newPathPtr, newPathPtr + newPathLen));
      const oldPath = resolvePath(oldDirFd, oldPathStr);
      const newPath = resolvePath(newDirFd, newPathStr);
      if (oldPath === null || newPath === null) return EBADF;

      const data = fileData(oldPath);
      if (!data) return ENOENT;

      // Copy data to new path, remove old
      writtenFiles.set(newPath, data);
      registerFile(newPath);
      writtenFiles.delete(oldPath);
      delete files[oldPath];
      // Remove from old parent dir listing
      const oldParts = oldPath.split("/");
      const oldName = oldParts.pop()!;
      const oldParent = oldParts.join("/");
      const oldSiblings = dirChildren.get(oldParent);
      if (oldSiblings) {
        const idx = oldSiblings.indexOf(oldName);
        if (idx !== -1) oldSiblings.splice(idx, 1);
      }
      return ESUCCESS;
    },

    path_symlink(): number { return ENOSYS; },

    path_unlink_file(dirFd: number, pathPtr: number, pathLen: number): number {
      const pathStr = decoder.decode(mem().subarray(pathPtr, pathPtr + pathLen));
      const fullPath = resolvePath(dirFd, pathStr);
      if (fullPath === null) return EBADF;
      if (!fileExists(fullPath)) return ENOENT;
      writtenFiles.delete(fullPath);
      delete files[fullPath];
      // Remove from parent dir listing
      const parts = fullPath.split("/");
      const name = parts.pop()!;
      const parent = parts.join("/");
      const siblings = dirChildren.get(parent);
      if (siblings) {
        const idx = siblings.indexOf(name);
        if (idx !== -1) siblings.splice(idx, 1);
      }
      return ESUCCESS;
    },

    poll_oneoff(): number { return ENOSYS; },
    proc_raise(): number { return ENOSYS; },
    sched_yield(): number { return ESUCCESS; },
    sock_recv(): number { return ENOSYS; },
    sock_send(): number { return ENOSYS; },
    sock_shutdown(): number { return ENOSYS; },
    sock_accept(): number { return ENOSYS; },

    random_get(bufPtr: number, bufLen: number): number {
      crypto.getRandomValues(new Uint8Array(getMemory().buffer, bufPtr, bufLen));
      return ESUCCESS;
    },

    proc_exit(code: number) {
      throw new ProcExit(code);
    },
  };

  return {
    imports,
    getStdout(): Uint8Array {
      let len = 0;
      for (const c of stdoutChunks) len += c.length;
      const result = new Uint8Array(len);
      let off = 0;
      for (const c of stdoutChunks) { result.set(c, off); off += c.length; }
      return result;
    },
    getStderr(): Uint8Array {
      let len = 0;
      for (const c of stderrChunks) len += c.length;
      const result = new Uint8Array(len);
      let off = 0;
      for (const c of stderrChunks) { result.set(c, off); off += c.length; }
      return result;
    },
    getWrittenFiles(): Map<string, Uint8Array> {
      return writtenFiles;
    },
  };
}

// Run Python WASM and return the result (does not throw)
function runWasm(
  args: string[],
  env: Record<string, string>,
  files: Record<string, Uint8Array>
): WasiResult {
  let memory: WebAssembly.Memory | undefined;
  const wasi = createWasi(args, env, files, () => memory!);

  try {
    const instance = new WebAssembly.Instance(pythonWasm, {
      wasi_snapshot_preview1: wasi.imports,
    });
    memory = instance.exports.memory as WebAssembly.Memory;
    const start = instance.exports._start as () => void;
    start();
    return {
      exitCode: 0,
      stdout: wasi.getStdout(),
      stderr: wasi.getStderr(),
      files,
      writtenFiles: wasi.getWrittenFiles(),
    };
  } catch (e: unknown) {
    if (e instanceof ProcExit) {
      return {
        exitCode: e.code,
        stdout: wasi.getStdout(),
        stderr: wasi.getStderr(),
        files,
        writtenFiles: wasi.getWrittenFiles(),
      };
    }
    throw e;
  }
}

// Base64 encode/decode for fetch response serialization
function base64Encode(data: Uint8Array): string {
  let binary = "";
  for (let i = 0; i < data.length; i++) {
    binary += String.fromCharCode(data[i]);
  }
  return btoa(binary);
}

function base64Decode(str: string): Uint8Array {
  const binary = atob(str);
  const bytes = new Uint8Array(binary.length);
  for (let i = 0; i < binary.length; i++) {
    bytes[i] = binary.charCodeAt(i);
  }
  return bytes;
}

// Response cache key: use request index from the pending array.
// Avoids hash collisions and signed/unsigned mismatches between JS and Python.
function responseKey(index: number): string {
  return index.toString();
}

// Re-execution trampoline: run Python, catch exit 254, do fetches, re-run
const EXIT_NEEDS_FETCH = 254;
const MAX_TRAMPOLINE_ROUNDS = 10;
const PENDING_FETCHES_PATH = "tmp/_pymode_pending_fetches.json";
const FETCH_RESPONSES_DIR = "tmp/_pymode_fetch_responses";
const PENDING_TCP_OPS_PATH = "tmp/_pymode_tcp_ops.json";
const TCP_RESPONSES_DIR = "tmp/_pymode_tcp_responses";

// Replay a TCP ops log with persistent connections.
// Connections stay open across operations. Each recv writes its response
// to the VFS so the next Python run can find it.
async function replayTcpOps(
  ops: TcpOp[],
  files: Record<string, Uint8Array>,
  encoder: TextEncoder
): Promise<void> {
  const connections = new Map<string, { socket: any; writer: WritableStreamDefaultWriter; reader: ReadableStreamDefaultReader }>();

  for (const op of ops) {
    switch (op.op) {
      case "connect": {
        if (!connections.has(op.connId)) {
          const socket = connect({ hostname: op.host!, port: op.port! });
          const writer = socket.writable.getWriter();
          const reader = socket.readable.getReader();
          connections.set(op.connId, { socket, writer, reader });
        }
        break;
      }
      case "send": {
        const conn = connections.get(op.connId);
        if (!conn) throw new Error(`TCP send on unknown connection: ${op.connId}`);
        const data = base64Decode(op.dataBase64!);
        await conn.writer.write(data);
        break;
      }
      case "recv": {
        const conn = connections.get(op.connId);
        if (!conn) throw new Error(`TCP recv on unknown connection: ${op.connId}`);
        const respPath = `${TCP_RESPONSES_DIR}/${op.recvId}`;

        // Always read from the socket to keep the protocol in sync,
        // even if we already have a cached response from a previous round.
        const chunks: Uint8Array[] = [];
        let totalLen = 0;
        const bufsize = op.bufsize || 65536;

        const timeoutPromise = new Promise<{ value: undefined; done: true }>((resolve) =>
          setTimeout(() => resolve({ value: undefined, done: true }), 10000)
        );

        // Read at least one chunk — database protocols send discrete messages
        while (totalLen < bufsize) {
          const result = await Promise.race([conn.reader.read(), timeoutPromise]);
          if (result.done || !result.value) break;
          chunks.push(result.value);
          totalLen += result.value.length;
          break;
        }

        // Only write to VFS if not already cached
        if (!files[respPath]) {
          const recvData = new Uint8Array(totalLen);
          let off = 0;
          for (const c of chunks) { recvData.set(c, off); off += c.length; }
          const meta = JSON.stringify({ dataBase64: base64Encode(recvData) });
          files[respPath] = encoder.encode(meta);
        }
        break;
      }
      case "close": {
        const conn = connections.get(op.connId);
        if (conn) {
          try {
            conn.writer.releaseLock();
            conn.reader.releaseLock();
            await conn.socket.close();
          } catch { /* ignore close errors */ }
          connections.delete(op.connId);
        }
        break;
      }
    }
  }

  // Close any connections still open (Python may not have closed them yet)
  for (const [, conn] of connections) {
    try {
      conn.writer.releaseLock();
      conn.reader.releaseLock();
      await conn.socket.close();
    } catch { /* ignore */ }
  }
}

const DATA_PREFIX = "data/";

// Load /data files from CF KV into the VFS
async function loadDataFromKV(
  kv: KVNamespace,
  files: Record<string, Uint8Array>
): Promise<void> {
  let cursor: string | undefined;
  do {
    const list = await kv.list({ cursor });
    const fetches = list.keys.map(async (key) => {
      const value = await kv.get(key.name, "arrayBuffer");
      if (value) {
        files[`${DATA_PREFIX}${key.name}`] = new Uint8Array(value);
      }
    });
    await Promise.all(fetches);
    cursor = list.list_complete ? undefined : list.cursor;
  } while (cursor);
}

// Flush dirty /data files from VFS back to CF KV
async function flushDataToKV(
  kv: KVNamespace,
  writtenFiles: Map<string, Uint8Array>
): Promise<void> {
  const writes: Promise<void>[] = [];
  writtenFiles.forEach((data, path) => {
    if (path.startsWith(DATA_PREFIX)) {
      const key = path.slice(DATA_PREFIX.length);
      writes.push(kv.put(key, data));
    }
  });
  await Promise.all(writes);
}

// Replay TCP ops via TcpPoolDO — persistent connections across trampoline rounds.
// All ops in a single replayOps() call = 1 billed DO request per host:port.
async function replayTcpOpsViaDO(
  ops: TcpOp[],
  files: Record<string, Uint8Array>,
  encoder: TextEncoder,
  tcpPool: DurableObjectNamespace
): Promise<void> {
  // Build connId → host:port mapping from connect ops
  const connHostPort = new Map<string, string>();
  for (const op of ops) {
    if (op.op === "connect" && op.host && op.port) {
      connHostPort.set(op.connId, `${op.host}:${op.port}`);
    }
  }

  // Group ops by their DO instance (keyed by host:port).
  // Each host:port gets its own TcpPoolDO with persistent connections.
  const opsByDO = new Map<string, TcpOp[]>();
  for (const op of ops) {
    const hostPort = connHostPort.get(op.connId);
    if (!hostPort) continue; // orphan op without a connect — skip
    if (!opsByDO.has(hostPort)) opsByDO.set(hostPort, []);
    opsByDO.get(hostPort)!.push(op);
  }

  // Execute ops on each DO in parallel (different host:port = different DO)
  const promises: Promise<void>[] = [];

  opsByDO.forEach((doOps, hostPort) => {
    promises.push((async () => {
      // Filter to only new ops (skip recvs that already have cached responses)
      const newOps: TcpOp[] = [];
      for (const op of doOps) {
        if (op.op === "recv" && op.recvId !== undefined) {
          const respPath = `${TCP_RESPONSES_DIR}/${op.recvId}`;
          if (files[respPath]) continue; // cached from previous round
        }
        newOps.push(op);
      }

      if (newOps.length === 0) return;

      const doId = tcpPool.idFromName(hostPort);
      const doInstance = tcpPool.get(doId) as any;

      try {
        const recvResults: Record<number, string> = await doInstance.replayOps(newOps);

        for (const [recvIdStr, dataBase64] of Object.entries(recvResults)) {
          const recvId = Number(recvIdStr);
          const respPath = `${TCP_RESPONSES_DIR}/${recvId}`;
          if (!files[respPath]) {
            const meta = JSON.stringify({ dataBase64 });
            files[respPath] = encoder.encode(meta);
          }
        }
      } catch (tcpErr) {
        const lastRecv = [...newOps].reverse().find(op => op.op === "recv");
        if (lastRecv && lastRecv.recvId !== undefined) {
          const meta = JSON.stringify({
            error: tcpErr instanceof Error ? tcpErr.message : String(tcpErr),
            dataBase64: "",
          });
          files[`${TCP_RESPONSES_DIR}/${lastRecv.recvId}`] = encoder.encode(meta);
        }
      }
    })());
  });

  await Promise.all(promises);
}

async function runPythonWithFetch(
  code: string,
  baseFiles: Record<string, Uint8Array>,
  kv?: KVNamespace,
  pythonPath: string = "/stdlib",
  tcpPool?: DurableObjectNamespace
): Promise<{ stdout: Uint8Array; stderr: Uint8Array; exitCode: number }> {
  const encoder = new TextEncoder();
  const decoder = new TextDecoder();
  const files = { ...baseFiles };

  // Load persistent /data from KV before first run
  if (kv) {
    await loadDataFromKV(kv, files);
  }

  for (let round = 0; round < MAX_TRAMPOLINE_ROUNDS; round++) {
    const result = runWasm(
      ["python", "-S", "-c", code],
      { PYTHONPATH: pythonPath, PYTHONDONTWRITEBYTECODE: "1", PYTHONNOUSERSITE: "1" },
      files
    );

    if (result.exitCode !== EXIT_NEEDS_FETCH) {
      // Flush dirty /data files to KV on final exit
      if (kv) {
        await flushDataToKV(kv, result.writtenFiles);
      }
      return { stdout: result.stdout, stderr: result.stderr, exitCode: result.exitCode };
    }

    // Python exited 254 — it wrote pending fetch requests to VFS
    // Merge written files back so we can read the pending fetches
    result.writtenFiles.forEach((data, path) => {
      files[path] = data;
    });

    const pendingFetchRaw = files[PENDING_FETCHES_PATH];
    const pendingTcpOpsRaw = files[PENDING_TCP_OPS_PATH];

    if (!pendingFetchRaw && !pendingTcpOpsRaw) {
      // Exit 254 but no pending requests — treat as error
      return { stdout: result.stdout, stderr: result.stderr, exitCode: result.exitCode };
    }

    // Handle HTTP fetches
    if (pendingFetchRaw) {
      const pending: Array<{
        url: string; method: string; headers?: Record<string, string>;
        body?: string; bodyIsBase64?: boolean;
      }> = JSON.parse(decoder.decode(pendingFetchRaw));

      if (pending.length > 0) {
        const responses = await Promise.all(
          pending.map((req) => {
            let reqBody: string | Uint8Array | undefined = req.body ?? undefined;
            if (req.bodyIsBase64 && req.body) {
              reqBody = base64Decode(req.body);
            }
            return fetch(req.url, {
              method: req.method || "GET",
              headers: req.headers,
              body: reqBody,
            });
          })
        );

        for (let i = 0; i < pending.length; i++) {
          const key = responseKey(i);
          const body = new Uint8Array(await responses[i].arrayBuffer());
          const meta = JSON.stringify({
            url: pending[i].url,
            method: pending[i].method || "GET",
            status: responses[i].status,
            headers: Object.fromEntries([...responses[i].headers.entries()]),
            bodyBase64: base64Encode(body),
          });
          files[`${FETCH_RESPONSES_DIR}/${key}`] = encoder.encode(meta);
        }
      }
      delete files[PENDING_FETCHES_PATH];
    }

    // Handle TCP operations — use TcpPoolDO for persistent connections when
    // available, fall back to raw socket replay when DO binding is not configured
    if (pendingTcpOpsRaw) {
      const ops: TcpOp[] = JSON.parse(decoder.decode(pendingTcpOpsRaw));

      if (tcpPool) {
        await replayTcpOpsViaDO(ops, files, encoder, tcpPool);
      } else {
        try {
          await replayTcpOps(ops, files, encoder);
        } catch (tcpErr) {
          const lastRecv = [...ops].reverse().find(op => op.op === "recv");
          if (lastRecv && lastRecv.recvId !== undefined) {
            const meta = JSON.stringify({
              error: tcpErr instanceof Error ? tcpErr.message : String(tcpErr),
              dataBase64: "",
            });
            files[`${TCP_RESPONSES_DIR}/${lastRecv.recvId}`] = encoder.encode(meta);
          }
        }
      }
      delete files[PENDING_TCP_OPS_PATH];
    }
  }

  throw new Error("Too many fetch trampoline rounds (possible infinite loop)");
}

export default {
  async fetch(request: Request, env: Env): Promise<Response> {
    const url = new URL(request.url);
    let code: string;
    if (request.method === "POST") {
      code = await request.text();
    } else {
      code = url.searchParams.get("code") || "print('Hello from PyMode!')";
    }

    const encoder = new TextEncoder();
    const decoder = new TextDecoder();

    // Build file map: path -> Uint8Array
    const files: Record<string, Uint8Array> = {};
    for (const [path, content] of Object.entries(stdlibFS)) {
      files[path] = encoder.encode(content);
    }

    // If site-packages.zip is bundled, add it to the VFS
    // Python's zipimport will load packages directly from the zip
    let pythonPath = "/stdlib";
    if (sitePackagesData) {
      files["site-packages.zip"] = new Uint8Array(sitePackagesData);
      pythonPath = "/stdlib:/stdlib/site-packages.zip";
    }

    try {
      const result = await runPythonWithFetch(code, files, env.PYMODE_DATA, pythonPath, env.TCP_POOL);

      if (result.exitCode === 0) {
        const output = decoder.decode(result.stdout);
        return new Response(output || "(empty output)\n", {
          headers: { "Content-Type": "text/plain; charset=utf-8", "X-Powered-By": "PyMode" },
        });
      }

      const output = decoder.decode(result.stdout);
      const errors = decoder.decode(result.stderr);
      return new Response(output + errors, {
        status: 500,
        headers: { "Content-Type": "text/plain; charset=utf-8", "X-Powered-By": "PyMode" },
      });
    } catch (e: unknown) {
      const msg = e instanceof Error ? e.message : String(e);
      return new Response(`Error: ${msg}\n`, {
        status: 500,
        headers: { "Content-Type": "text/plain" },
      });
    }
  },
};
