import pythonWasm from "./python.wasm";
import { DurableObject } from "cloudflare:workers";
import { connect } from "cloudflare:sockets";
import { ProcExit, createWasi } from "./wasi";
import type { WasiResult } from "./wasi";
import { encoder as _encoder, decoder as _decoder, stdlibBin, stdlibDirIndex, extensionPackagesBin } from "./stdlib-bin";

// Re-export DOs so wrangler can find them
export { PythonDO } from "./python-do";
export { ThreadDO } from "./thread-do";

/** Block requests to private/internal networks (SSRF prevention). */
function isPrivateHost(hostname: string): boolean {
  if (/^(127\.|10\.|192\.168\.|172\.(1[6-9]|2\d|3[01])\.)/.test(hostname)) return true;
  if (/^169\.254\./.test(hostname)) return true;
  if (hostname === "localhost" || hostname === "[::1]" || hostname === "::1") return true;
  if (/^\[?fe80:/i.test(hostname) || /^\[?fc/i.test(hostname) || /^\[?fd/i.test(hostname)) return true;
  return false;
}

// User project files (generated by scripts/bundle-project.py)
// When no project is bundled, falls back to legacy code-string mode.
let userFilesModule: { entryModule: string; userFiles: Record<string, string> } | null = null;
try {
  // @ts-ignore — conditional import, generated at deploy time
  userFilesModule = require("./user-files");
} catch {
  // No project bundled — legacy mode
}

// Bundled third-party packages (generated by scripts/bundle-packages.ts).
// Loaded as a Data module (ArrayBuffer) via wrangler rules for *.zip.
// generate-stdlib-fs.ts creates an empty zip if no packages are bundled.
// @ts-ignore — Data module import (ArrayBuffer)
import sitePackagesZip from "./site-packages.zip";
const sitePackagesData: ArrayBuffer | undefined =
  sitePackagesZip.byteLength > 22 ? sitePackagesZip : undefined;
const sitePackagesBin: Uint8Array | undefined =
  sitePackagesData ? new Uint8Array(sitePackagesData) : undefined;

interface TcpOp {
  op: "connect" | "send" | "recv" | "close";
  connId: string;
  host?: string;
  port?: number;
  dataBase64?: string;
  recvId?: number;
  bufsize?: number;
}

// TcpPoolDO: Holds persistent TCP connections across trampoline rounds.
// One instance per host:port pair. Connection persists in memory as long as the
// DO stays alive (70-140s idle timeout, extendable via alarm heartbeat).
// This eliminates the need to replay full TCP conversations each round.
export class TcpPoolDO extends DurableObject {
  private connections = new Map<string, {
    socket: any;
    reader: ReadableStreamDefaultReader<Uint8Array>;
    writer: WritableStreamDefaultWriter<Uint8Array>;
  }>();

  async tcpConnect(connId: string, host: string, port: number): Promise<void> {
    if (this.connections.has(connId)) return; // already connected
    if (isPrivateHost(host)) throw new Error(`tcp_connect blocked: private host ${host}`);
    const socket = connect({ hostname: host, port });
    const writer = socket.writable.getWriter();
    const reader = socket.readable.getReader();
    this.connections.set(connId, { socket, writer, reader });
  }

  async tcpSend(connId: string, dataBase64: string): Promise<void> {
    const conn = this.connections.get(connId);
    if (!conn) throw new Error(`send on unknown connection: ${connId}`);
    await conn.writer.write(base64Decode(dataBase64));
  }

  async tcpRecv(connId: string, bufsize: number): Promise<string> {
    const conn = this.connections.get(connId);
    if (!conn) throw new Error(`recv on unknown connection: ${connId}`);

    const timeoutPromise = new Promise<{ value: undefined; done: true }>((resolve) =>
      setTimeout(() => resolve({ value: undefined, done: true }), 10000)
    );

    const result = await Promise.race([conn.reader.read(), timeoutPromise]);
    if (result.done || !result.value) return "";

    const bytes = result.value.slice(0, bufsize);
    let binary = "";
    for (let i = 0; i < bytes.length; i++) binary += String.fromCharCode(bytes[i]);
    return btoa(binary);
  }

  async tcpClose(connId: string): Promise<void> {
    const conn = this.connections.get(connId);
    if (!conn) return;
    try { conn.writer.releaseLock(); } catch {}
    try { conn.reader.releaseLock(); } catch {}
    try { conn.socket.close(); } catch {}
    this.connections.delete(connId);
  }

  // Replay a full ops log in a single RPC session (1 billed request).
  // Returns a map of recvId → base64-encoded response data.
  async replayOps(ops: TcpOp[]): Promise<Record<number, string>> {
    const recvResults: Record<number, string> = {};

    for (const op of ops) {
      switch (op.op) {
        case "connect":
          await this.tcpConnect(op.connId, op.host!, op.port!);
          break;
        case "send":
          await this.tcpSend(op.connId, op.dataBase64!);
          break;
        case "recv": {
          const data = await this.tcpRecv(op.connId, op.bufsize || 65536);
          recvResults[op.recvId!] = data;
          break;
        }
        case "close":
          await this.tcpClose(op.connId);
          break;
      }
    }

    return recvResults;
  }
}

// Custom synchronous WASI shim for running Python on CF Workers.
// Unlike @cloudflare/workers-wasi, this doesn't need asyncify because
// all syscalls are backed by an in-memory filesystem with zero I/O.

interface Env {
  PYMODE_DATA?: KVNamespace;
  TCP_POOL?: DurableObjectNamespace;
  PYTHON_DO?: DurableObjectNamespace;
  THREAD_DO?: DurableObjectNamespace;
  [key: string]: unknown;
}

// WASI implementation imported from ./wasi.ts

// Run Python WASM and return the result (does not throw).
// Uses async WebAssembly.instantiate() — workerd blocks synchronous
// instantiation for modules >4MB, and python.wasm is ~5.6MB.
async function runWasm(
  args: string[],
  env: Record<string, string>,
  files: Record<string, Uint8Array>,
  stdinData?: Uint8Array
): Promise<WasiResult> {
  let memory: WebAssembly.Memory | undefined;
  const wasi = createWasi(args, env, files, () => memory!, stdinData, stdlibDirIndex);

  // Minimal pymode.* imports for WASM linker compatibility.
  // In legacy mode, bindings are handled by the re-execution trampoline
  // or the _pymode.py polyfill — these just satisfy the WASM import table.
  const pymode: Record<string, Function> = {
    dl_open: () => -1, dl_sym: () => 0, dl_close: () => {}, dl_error: () => 0,
    tcp_connect: () => -1, tcp_send: () => -1, tcp_recv: () => -1, tcp_close: () => {},
    thread_spawn: () => -1, thread_join: () => -1,
    http_fetch_full: () => -1,
    kv_get: () => -1, kv_put: () => {}, kv_delete: () => {},
    kv_multi_get: () => -1, kv_multi_put: () => {},
    r2_get: () => -1, r2_put: () => {},
    d1_exec: () => -1, d1_batch: () => -1,
    env_get: () => -1, console_log: () => {},
    zerobuf_exchange_ptr: () => 0,
  };
  let exitCode = 0;
  try {
    const { instance } = await WebAssembly.instantiate(pythonWasm, {
      wasi_snapshot_preview1: wasi.imports,
      pymode,
    });
    memory = instance.exports.memory as WebAssembly.Memory;
    (instance.exports._start as () => void)();
  } catch (e: unknown) {
    if (e instanceof ProcExit) exitCode = e.code;
    else throw e;
  }
  return {
    exitCode,
    stdout: wasi.getStdout(),
    stderr: wasi.getStderr(),
    files,
    writtenFiles: wasi.getWrittenFiles(),
  };
}

// Base64 encode/decode for fetch response serialization
const PYMODE_TEXT_HEADERS = { "Content-Type": "text/plain; charset=utf-8", "X-Powered-By": "PyMode" } as const;

function textResponse(body: string, status = 200): Response {
  return new Response(body, { status, headers: PYMODE_TEXT_HEADERS });
}

function base64Encode(data: Uint8Array): string {
  let binary = "";
  for (let i = 0; i < data.length; i++) {
    binary += String.fromCharCode(data[i]);
  }
  return btoa(binary);
}

function base64Decode(str: string): Uint8Array {
  const binary = atob(str);
  const bytes = new Uint8Array(binary.length);
  for (let i = 0; i < binary.length; i++) {
    bytes[i] = binary.charCodeAt(i);
  }
  return bytes;
}

// Re-execution trampoline: run Python, catch exit 254, do fetches, re-run
const EXIT_NEEDS_FETCH = 254;
const MAX_TRAMPOLINE_ROUNDS = 10;
const PENDING_FETCHES_PATH = "tmp/_pymode_pending_fetches.json";
const FETCH_RESPONSES_DIR = "tmp/_pymode_fetch_responses";
const PENDING_TCP_OPS_PATH = "tmp/_pymode_tcp_ops.json";
const TCP_RESPONSES_DIR = "tmp/_pymode_tcp_responses";

// Replay a TCP ops log with persistent connections.
// Connections stay open across operations. Each recv writes its response
// to the VFS so the next Python run can find it.
async function replayTcpOps(
  ops: TcpOp[],
  files: Record<string, Uint8Array>,
): Promise<void> {
  const connections = new Map<string, { socket: any; writer: WritableStreamDefaultWriter; reader: ReadableStreamDefaultReader }>();

  for (const op of ops) {
    switch (op.op) {
      case "connect": {
        if (!connections.has(op.connId)) {
          if (isPrivateHost(op.host!)) throw new Error(`tcp_connect blocked: private host ${op.host}`);
          const socket = connect({ hostname: op.host!, port: op.port! });
          const writer = socket.writable.getWriter();
          const reader = socket.readable.getReader();
          connections.set(op.connId, { socket, writer, reader });
        }
        break;
      }
      case "send": {
        const conn = connections.get(op.connId);
        if (!conn) throw new Error(`TCP send on unknown connection: ${op.connId}`);
        const data = base64Decode(op.dataBase64!);
        await conn.writer.write(data);
        break;
      }
      case "recv": {
        const conn = connections.get(op.connId);
        if (!conn) throw new Error(`TCP recv on unknown connection: ${op.connId}`);
        const respPath = `${TCP_RESPONSES_DIR}/${op.recvId}`;

        // Always read from the socket to keep the protocol in sync,
        // even if we already have a cached response from a previous round.
        const timeoutPromise = new Promise<{ value: undefined; done: true }>((resolve) =>
          setTimeout(() => resolve({ value: undefined, done: true }), 10000)
        );

        const result = await Promise.race([conn.reader.read(), timeoutPromise]);
        const recvData = (!result.done && result.value) ? result.value : new Uint8Array(0);

        if (!files[respPath]) {
          const meta = JSON.stringify({ dataBase64: base64Encode(recvData) });
          files[respPath] = _encoder.encode(meta);
        }
        break;
      }
      case "close": {
        const conn = connections.get(op.connId);
        if (conn) {
          try {
            conn.writer.releaseLock();
            conn.reader.releaseLock();
            await conn.socket.close();
          } catch { /* ignore close errors */ }
          connections.delete(op.connId);
        }
        break;
      }
    }
  }

  // Close any connections still open (Python may not have closed them yet)
  for (const [, conn] of connections) {
    try {
      conn.writer.releaseLock();
      conn.reader.releaseLock();
      await conn.socket.close();
    } catch { /* ignore */ }
  }
}

const DATA_PREFIX = "data/";

// Load /data files from CF KV into the VFS
async function loadDataFromKV(
  kv: KVNamespace,
  files: Record<string, Uint8Array>
): Promise<void> {
  let cursor: string | undefined;
  do {
    const list = await kv.list({ cursor });
    const fetches = list.keys.map(async (key) => {
      const value = await kv.get(key.name, "arrayBuffer");
      if (value) {
        files[`${DATA_PREFIX}${key.name}`] = new Uint8Array(value);
      }
    });
    await Promise.all(fetches);
    cursor = list.list_complete ? undefined : list.cursor;
  } while (cursor);
}

// Flush dirty /data files from VFS back to CF KV
async function flushDataToKV(
  kv: KVNamespace,
  writtenFiles: Map<string, Uint8Array>
): Promise<void> {
  const writes: Promise<void>[] = [];
  writtenFiles.forEach((data, path) => {
    if (path.startsWith(DATA_PREFIX)) {
      const key = path.slice(DATA_PREFIX.length);
      writes.push(kv.put(key, data));
    }
  });
  await Promise.all(writes);
}

// Write a TCP error response to VFS for the last recv op in the list
function writeTcpError(ops: TcpOp[], err: unknown, files: Record<string, Uint8Array>): void {
  const lastRecv = [...ops].reverse().find(op => op.op === "recv");
  if (lastRecv && lastRecv.recvId !== undefined) {
    const meta = JSON.stringify({
      error: err instanceof Error ? err.message : String(err),
      dataBase64: "",
    });
    files[`${TCP_RESPONSES_DIR}/${lastRecv.recvId}`] = _encoder.encode(meta);
  }
}

// Replay TCP ops via TcpPoolDO — persistent connections across trampoline rounds.
// All ops in a single replayOps() call = 1 billed DO request per host:port.
async function replayTcpOpsViaDO(
  ops: TcpOp[],
  files: Record<string, Uint8Array>,
  tcpPool: DurableObjectNamespace
): Promise<void> {
  // Build connId → host:port mapping from connect ops
  const connHostPort = new Map<string, string>();
  for (const op of ops) {
    if (op.op === "connect" && op.host && op.port) {
      connHostPort.set(op.connId, `${op.host}:${op.port}`);
    }
  }

  // Group ops by their DO instance (keyed by host:port).
  // Each host:port gets its own TcpPoolDO with persistent connections.
  const opsByDO = new Map<string, TcpOp[]>();
  for (const op of ops) {
    const hostPort = connHostPort.get(op.connId);
    if (!hostPort) continue; // orphan op without a connect — skip
    if (!opsByDO.has(hostPort)) opsByDO.set(hostPort, []);
    opsByDO.get(hostPort)!.push(op);
  }

  // Execute ops on each DO in parallel (different host:port = different DO)
  const promises: Promise<void>[] = [];

  opsByDO.forEach((doOps, hostPort) => {
    promises.push((async () => {
      // Filter to only new ops (skip recvs that already have cached responses)
      const newOps: TcpOp[] = [];
      for (const op of doOps) {
        if (op.op === "recv" && op.recvId !== undefined) {
          const respPath = `${TCP_RESPONSES_DIR}/${op.recvId}`;
          if (files[respPath]) continue; // cached from previous round
        }
        newOps.push(op);
      }

      if (newOps.length === 0) return;

      const doId = tcpPool.idFromName(hostPort);
      const doInstance = tcpPool.get(doId) as any;

      try {
        const recvResults: Record<number, string> = await doInstance.replayOps(newOps);

        for (const [recvIdStr, dataBase64] of Object.entries(recvResults)) {
          const recvId = Number(recvIdStr);
          const respPath = `${TCP_RESPONSES_DIR}/${recvId}`;
          if (!files[respPath]) {
            const meta = JSON.stringify({ dataBase64 });
            files[respPath] = _encoder.encode(meta);
          }
        }
      } catch (tcpErr) {
        writeTcpError(newOps, tcpErr, files);
      }
    })());
  });

  await Promise.all(promises);
}

async function runPythonWithFetch(
  code: string,
  baseFiles: Record<string, Uint8Array>,
  kv?: KVNamespace,
  pythonPath: string = "/stdlib",
  tcpPool?: DurableObjectNamespace
): Promise<{ stdout: Uint8Array; stderr: Uint8Array; exitCode: number }> {
  const files = { ...baseFiles };

  // Load persistent /data from KV before first run
  if (kv) {
    await loadDataFromKV(kv, files);
  }

  // WASI compat bootstrap — patches os.getpid etc. before user code
  const bootstrappedCode = "import _wasi_compat\n" + code;

  for (let round = 0; round < MAX_TRAMPOLINE_ROUNDS; round++) {
    const result = await runWasm(
      ["python", "-S", "-c", bootstrappedCode],
      { PYTHONPATH: pythonPath, PYTHONDONTWRITEBYTECODE: "1", PYTHONNOUSERSITE: "1" },
      files
    );

    if (result.exitCode !== EXIT_NEEDS_FETCH) {
      // Flush dirty /data files to KV on final exit
      if (kv) {
        await flushDataToKV(kv, result.writtenFiles);
      }
      return { stdout: result.stdout, stderr: result.stderr, exitCode: result.exitCode };
    }

    // Python exited 254 — it wrote pending fetch requests to VFS
    // Merge written files back so we can read the pending fetches
    result.writtenFiles.forEach((data, path) => {
      files[path] = data;
    });

    const pendingFetchRaw = files[PENDING_FETCHES_PATH];
    const pendingTcpOpsRaw = files[PENDING_TCP_OPS_PATH];

    if (!pendingFetchRaw && !pendingTcpOpsRaw) {
      // Exit 254 but no pending requests — treat as error
      return { stdout: result.stdout, stderr: result.stderr, exitCode: result.exitCode };
    }

    // Handle HTTP fetches
    if (pendingFetchRaw) {
      const pending: Array<{
        url: string; method: string; headers?: Record<string, string>;
        body?: string; bodyIsBase64?: boolean;
      }> = JSON.parse(_decoder.decode(pendingFetchRaw));

      if (pending.length > 0) {
        const responses = await Promise.all(
          pending.map((req) => {
            const parsed = new URL(req.url);
            if (!["http:", "https:"].includes(parsed.protocol)) {
              throw new Error(`fetch blocked: unsupported protocol ${parsed.protocol}`);
            }
            if (isPrivateHost(parsed.hostname)) {
              throw new Error(`fetch blocked: private host ${parsed.hostname}`);
            }
            let reqBody: string | Uint8Array | undefined = req.body ?? undefined;
            if (req.bodyIsBase64 && req.body) {
              reqBody = base64Decode(req.body);
            }
            return fetch(req.url, {
              method: req.method || "GET",
              headers: req.headers,
              body: reqBody,
            });
          })
        );

        for (let i = 0; i < pending.length; i++) {
          const body = new Uint8Array(await responses[i].arrayBuffer());
          const meta = JSON.stringify({
            url: pending[i].url,
            method: pending[i].method || "GET",
            status: responses[i].status,
            headers: Object.fromEntries([...responses[i].headers.entries()]),
            bodyBase64: base64Encode(body),
          });
          files[`${FETCH_RESPONSES_DIR}/${i}`] = _encoder.encode(meta);
        }
      }
      delete files[PENDING_FETCHES_PATH];
    }

    // Handle TCP operations — use TcpPoolDO for persistent connections when
    // available, fall back to raw socket replay when DO binding is not configured
    if (pendingTcpOpsRaw) {
      const ops: TcpOp[] = JSON.parse(_decoder.decode(pendingTcpOpsRaw));

      if (tcpPool) {
        await replayTcpOpsViaDO(ops, files, tcpPool);
      } else {
        try {
          await replayTcpOps(ops, files);
        } catch (tcpErr) {
          writeTcpError(ops, tcpErr, files);
        }
      }
      delete files[PENDING_TCP_OPS_PATH];
    }
  }

  throw new Error("Too many fetch trampoline rounds (possible infinite loop)");
}

/**
 * Serialize a CF Request into JSON for the Python handler.
 * Python reads this from stdin, constructs a Request object, calls on_fetch().
 */
async function serializeRequest(request: Request, env: Env): Promise<string> {
  const headers: Record<string, string> = {};
  request.headers.forEach((value, key) => { headers[key] = value; });

  let body = "";
  if (request.method !== "GET" && request.method !== "HEAD") {
    try { body = await request.text(); } catch { /* empty body */ }
  }

  // Expose env bindings as simple key-value (secrets/vars only, not DO/KV objects)
  const envData: Record<string, string> = {};
  for (const [key, val] of Object.entries(env)) {
    if (typeof val === "string") envData[key] = val;
  }

  return JSON.stringify({
    request: {
      method: request.method,
      url: request.url,
      headers,
      body,
    },
    env: envData,
  });
}

/**
 * Parse Python's stdout JSON into a CF Response.
 * Python handler writes serialized Response to stdout.
 */
function deserializeResponse(stdout: string, stderr: string): Response {
  if (!stdout.trim()) {
    return textResponse(stderr || "(empty response)\n", 500);
  }

  try {
    const data = JSON.parse(stdout);
    let body: BodyInit = data.body || "";

    // Handle binary responses (base64-encoded by Python)
    if (data.bodyIsBinary && data.body) {
      body = base64Decode(data.body);
    }

    const headers: Record<string, string> = data.headers || {};
    headers["X-Powered-By"] = "PyMode";

    return new Response(body, {
      status: data.status || 200,
      headers,
    });
  } catch {
    // stdout wasn't valid JSON — return as plain text (legacy mode output)
    return textResponse(stdout);
  }
}

export default {
  async fetch(request: Request, env: Env): Promise<Response> {
    // Build VFS: stdlib + pymode runtime (pre-encoded at module load)
    const files: Record<string, Uint8Array> = { ...stdlibBin };

    // Mount user project files at /app/ in VFS
    if (userFilesModule) {
      for (const [path, content] of Object.entries(userFilesModule.userFiles)) {
        files[path] = _encoder.encode(content);
      }
    }

    // Site-packages (pre-created Uint8Array views, no copy per request)
    let pythonPath = "/stdlib:/stdlib/app";
    if (sitePackagesBin) {
      files["site-packages.zip"] = sitePackagesBin;
      pythonPath += ":/stdlib/site-packages.zip";
    }
    if (extensionPackagesBin) {
      files["extension-site-packages.zip"] = extensionPackagesBin;
      pythonPath += ":/stdlib/extension-site-packages.zip";
    }

    try {
      // ---- Project mode: route through PythonDO for full host imports ----
      if (userFilesModule) {
        const requestJson = await serializeRequest(request, env);

        // Route through PythonDO if available (full host imports + Asyncify).
        // Only serializable data crosses the RPC boundary.
        if (env.PYTHON_DO) {
          const doId = env.PYTHON_DO.idFromName("default");
          const pythonDO = env.PYTHON_DO.get(doId) as any;
          const result = await pythonDO.handleRequest(
            userFilesModule.entryModule,
            userFilesModule.userFiles,
            pythonPath,
            requestJson,
            sitePackagesData,
          );

          if (result.stderr) console.error("[PyMode stderr]", result.stderr);
          return deserializeResponse(result.stdout, result.stderr);
        }

        // Fallback: run without host imports (no KV/R2/D1/TCP, but works)
        const stdinData = _encoder.encode(requestJson);
        const result = await runWasm(
          ["python", "-S", "-m", "pymode._handler", userFilesModule.entryModule],
          { PYTHONPATH: pythonPath, PYTHONDONTWRITEBYTECODE: "1", PYTHONNOUSERSITE: "1" },
          files,
          stdinData
        );

        const stdout = _decoder.decode(result.stdout);
        const stderr = _decoder.decode(result.stderr);
        if (stderr) console.error("[PyMode stderr]", stderr);

        if (env.PYMODE_DATA) {
          await flushDataToKV(env.PYMODE_DATA, result.writtenFiles);
        }

        return deserializeResponse(stdout, stderr);
      }

      // ---- Legacy mode: POST code string ----
      let code: string;
      if (request.method === "POST") {
        code = await request.text();
      } else {
        const url = new URL(request.url);
        code = url.searchParams.get("code") || "print('Hello from PyMode!')";
      }

      // Route through PythonDO if available (gives legacy mode host imports too)
      if (env.PYTHON_DO) {
        const doId = env.PYTHON_DO.idFromName("default");
        const pythonDO = env.PYTHON_DO.get(doId) as any;
        const result = await pythonDO.executeCode(code, sitePackagesData);

        if (result.exitCode === 0) {
          return textResponse(result.stdout || "(empty output)\n");
        }
        return textResponse(result.stdout + result.stderr, 500);
      }

      // Fallback: run in stateless worker without host imports
      const result = await runPythonWithFetch(code, files, env.PYMODE_DATA, pythonPath, env.TCP_POOL);

      const output = _decoder.decode(result.stdout);
      if (result.exitCode === 0) {
        return textResponse(output || "(empty output)\n");
      }
      return textResponse(output + _decoder.decode(result.stderr), 500);
    } catch (e: unknown) {
      console.error("PyMode error:", e);
      return new Response("Internal Server Error\n", {
        status: 500,
        headers: { "Content-Type": "text/plain" },
      });
    }
  },
};
