#!/usr/bin/env python3
"""Bundle a PyMode project's .py files into a TypeScript module for the worker.

This is the deploy-time step that takes your Python project and packages it
into the worker. Similar to how CF Python Workers bundles .py files at deploy.

Input:  A project directory containing .py files (and optionally pyproject.toml)
Output: worker/src/user-files.ts — a map of path -> content for the VFS

Usage:
    python3 scripts/bundle-project.py ./my-project
    python3 scripts/bundle-project.py ./my-project src/entry.py
"""

import json
import os
import sys

SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
ROOT_DIR = os.path.dirname(SCRIPT_DIR)
WORKER_DIR = os.path.join(ROOT_DIR, "worker")

GREEN = "\033[0;32m"
YELLOW = "\033[1;33m"
RED = "\033[0;31m"
NC = "\033[0m"


def info(msg: str):
    print(f"{GREEN}[INFO]{NC} {msg}")


def warn(msg: str):
    print(f"{YELLOW}[WARN]{NC} {msg}")


def error(msg: str):
    print(f"{RED}[ERROR]{NC} {msg}", file=sys.stderr)
    sys.exit(1)


def find_entry_point(project_dir: str) -> str:
    """Find the entry point for the project."""
    # Check pyproject.toml for [tool.pymode] main
    pyproject = os.path.join(project_dir, "pyproject.toml")
    if os.path.isfile(pyproject):
        try:
            import tomllib
            with open(pyproject, "rb") as f:
                data = tomllib.load(f)
            entry = data.get("tool", {}).get("pymode", {}).get("main", "")
            if entry:
                return entry
        except Exception:
            pass

    # Fallback: check common entry points
    for candidate in ["src/entry.py", "entry.py", "app.py", "main.py", "worker.py"]:
        if os.path.isfile(os.path.join(project_dir, candidate)):
            return candidate

    error(
        "No entry point found. Create src/entry.py or specify one: "
        f"python3 {sys.argv[0]} <project-dir> <entry.py>"
    )
    return ""  # unreachable


def collect_py_files(project_dir: str) -> list[str]:
    """Collect all .py files, excluding __pycache__, .venv, node_modules."""
    py_files = []
    for root, dirs, files in os.walk(project_dir):
        dirs[:] = [
            d for d in dirs
            if d not in ("__pycache__", ".venv", "node_modules")
        ]
        for f in files:
            if f.endswith(".py"):
                py_files.append(os.path.join(root, f))
    return sorted(py_files)


def main():
    project_dir = os.path.abspath(sys.argv[1] if len(sys.argv) > 1 else ".")
    entry_point = sys.argv[2] if len(sys.argv) > 2 else ""

    if not os.path.isdir(project_dir):
        error(f"Project directory not found: {project_dir}")

    if not entry_point:
        entry_point = find_entry_point(project_dir)

    entry_file = os.path.join(project_dir, entry_point)
    if not os.path.isfile(entry_file):
        error(f"Entry point not found: {entry_file}")

    # Convert entry point path to Python module name
    entry_module = entry_point.removesuffix(".py").replace("/", ".")

    info(f"Project:     {project_dir}")
    info(f"Entry point: {entry_point}")
    info(f"Module:      {entry_module}")

    py_files = collect_py_files(project_dir)
    if not py_files:
        error(f"No .py files found in {project_dir}")

    info(f"Found {len(py_files)} Python files")

    # Generate user-files.ts
    output = os.path.join(WORKER_DIR, "src", "user-files.ts")
    with open(output, "w") as f:
        f.write("// Auto-generated by scripts/bundle-project.py — do not edit.\n")
        f.write("// User project files mounted at /app/ in the VFS.\n\n")
        f.write(f'export const entryModule = "{entry_module}";\n\n')
        f.write("export const userFiles: Record<string, string> = {\n")

        for filepath in py_files:
            rel_path = os.path.relpath(filepath, project_dir)
            with open(filepath, "r") as src:
                content = src.read()
            f.write(f'  "app/{rel_path}": {json.dumps(content)},\n')

        f.write("};\n")

    info(f"Generated {output}")
    info(f"  Entry module: {entry_module}")
    info(f"  Files bundled: {len(py_files)}")

    # Check for pyproject.toml dependencies
    pyproject = os.path.join(project_dir, "pyproject.toml")
    if os.path.isfile(pyproject):
        try:
            import tomllib
            with open(pyproject, "rb") as f:
                data = tomllib.load(f)
            deps = data.get("project", {}).get("dependencies", [])
            if deps:
                warn(f"Dependencies found: {', '.join(deps)}")
                warn("Run scripts/bundle-packages.py to bundle them into site-packages.zip")
        except Exception:
            pass

    print()
    info("Done. Deploy with: cd worker && npx wrangler deploy")


if __name__ == "__main__":
    main()
