#!/usr/bin/env bash
# Bundle a PyMode project's .py files into a TypeScript module for the worker.
#
# This is the deploy-time step that takes your Python project and packages it
# into the worker. Similar to how CF Python Workers bundles .py files at deploy.
#
# Input:  A project directory containing .py files (and optionally pyproject.toml)
# Output: worker/src/user-files.ts — a map of path -> content for the VFS
#
# Usage:
#   ./scripts/bundle-project.sh ./my-project
#   ./scripts/bundle-project.sh ./my-project src/entry.py
#
# The entry point defaults to the "main" field in pyproject.toml,
# or src/entry.py, or entry.py, or app.py, or main.py.

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
ROOT_DIR="$(dirname "$SCRIPT_DIR")"
WORKER_DIR="$ROOT_DIR/worker"

RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m'

info() { echo -e "${GREEN}[INFO]${NC} $*"; }
warn() { echo -e "${YELLOW}[WARN]${NC} $*"; }
error() { echo -e "${RED}[ERROR]${NC} $*"; exit 1; }

PROJECT_DIR="${1:-.}"
ENTRY_POINT="${2:-}"

# Resolve project dir
PROJECT_DIR="$(cd "$PROJECT_DIR" && pwd)"
[ -d "$PROJECT_DIR" ] || error "Project directory not found: $PROJECT_DIR"

# Find entry point
if [ -z "$ENTRY_POINT" ]; then
    # Check pyproject.toml for [tool.pymode] main
    if [ -f "$PROJECT_DIR/pyproject.toml" ]; then
        ENTRY_POINT=$(python3 -c "
import tomllib, sys
with open('$PROJECT_DIR/pyproject.toml', 'rb') as f:
    d = tomllib.load(f)
print(d.get('tool', {}).get('pymode', {}).get('main', ''))
" 2>/dev/null || true)
    fi

    # Fallback: check common entry points
    if [ -z "$ENTRY_POINT" ]; then
        for candidate in "src/entry.py" "entry.py" "app.py" "main.py" "worker.py"; do
            if [ -f "$PROJECT_DIR/$candidate" ]; then
                ENTRY_POINT="$candidate"
                break
            fi
        done
    fi

    [ -n "$ENTRY_POINT" ] || error "No entry point found. Create src/entry.py or specify one: $0 <project-dir> <entry.py>"
fi

# Verify entry point exists
[ -f "$PROJECT_DIR/$ENTRY_POINT" ] || error "Entry point not found: $PROJECT_DIR/$ENTRY_POINT"

# Convert entry point path to Python module name
# src/entry.py -> src.entry, app.py -> app
ENTRY_MODULE=$(echo "$ENTRY_POINT" | sed 's/\.py$//' | sed 's/\//./g')

info "Project:     $PROJECT_DIR"
info "Entry point: $ENTRY_POINT"
info "Module:      $ENTRY_MODULE"

# Collect all .py files
PY_FILES=()
while IFS= read -r -d '' file; do
    PY_FILES+=("$file")
done < <(find "$PROJECT_DIR" -name "*.py" -not -path "*/__pycache__/*" -not -path "*/.venv/*" -not -path "*/node_modules/*" -print0)

if [ ${#PY_FILES[@]} -eq 0 ]; then
    error "No .py files found in $PROJECT_DIR"
fi

info "Found ${#PY_FILES[@]} Python files"

# Generate user-files.ts
OUTPUT="$WORKER_DIR/src/user-files.ts"
cat > "$OUTPUT" << 'HEADER'
// Auto-generated by scripts/bundle-project.sh — do not edit.
// User project files mounted at /app/ in the VFS.

HEADER

# Write entry module name
echo "export const entryModule = \"$ENTRY_MODULE\";" >> "$OUTPUT"
echo "" >> "$OUTPUT"

# Write file map
echo "export const userFiles: Record<string, string> = {" >> "$OUTPUT"

for file in "${PY_FILES[@]}"; do
    # Get path relative to project dir
    rel_path="${file#$PROJECT_DIR/}"

    # Escape the content for a JS template literal
    # We use JSON.stringify via python for proper escaping
    escaped=$(python3 -c "
import json, sys
with open('$file', 'r') as f:
    content = f.read()
print(json.dumps(content))
")

    echo "  \"app/$rel_path\": $escaped," >> "$OUTPUT"
done

echo "};" >> "$OUTPUT"

info "Generated $OUTPUT"
info "  Entry module: $ENTRY_MODULE"
info "  Files bundled: ${#PY_FILES[@]}"

# Check for pyproject.toml dependencies
if [ -f "$PROJECT_DIR/pyproject.toml" ]; then
    DEPS=$(python3 -c "
import tomllib
with open('$PROJECT_DIR/pyproject.toml', 'rb') as f:
    d = tomllib.load(f)
deps = d.get('project', {}).get('dependencies', [])
if deps:
    print(', '.join(deps))
" 2>/dev/null || true)

    if [ -n "$DEPS" ]; then
        warn "Dependencies found: $DEPS"
        warn "Run scripts/bundle-packages.py to bundle them into site-packages.zip"
    fi
fi

echo ""
info "Done. Deploy with: cd worker && npx wrangler deploy"
