#!/usr/bin/env npx tsx
/**
 * Bundle a PyMode project's .py files into a TypeScript module for the worker.
 *
 * This is the deploy-time step that takes your Python project and packages it
 * into the worker. Similar to how CF Python Workers bundles .py files at deploy.
 *
 * Input:  A project directory containing .py files (and optionally pyproject.toml)
 * Output: worker/src/user-files.ts — a map of path -> content for the VFS
 *
 * Usage:
 *     npx tsx scripts/bundle-project.ts ./my-project
 *     npx tsx scripts/bundle-project.ts ./my-project src/entry.py
 */

import * as fs from "node:fs";
import * as path from "node:path";
import { fileURLToPath } from "node:url";

const SCRIPT_DIR = path.dirname(fileURLToPath(import.meta.url));
const ROOT_DIR = path.dirname(SCRIPT_DIR);
const WORKER_DIR = path.join(ROOT_DIR, "worker");

const GREEN = "\x1b[0;32m";
const YELLOW = "\x1b[1;33m";
const RED = "\x1b[0;31m";
const NC = "\x1b[0m";

function info(msg: string): void {
  console.log(`${GREEN}[INFO]${NC} ${msg}`);
}

function warn(msg: string): void {
  console.log(`${YELLOW}[WARN]${NC} ${msg}`);
}

function error(msg: string): never {
  console.error(`${RED}[ERROR]${NC} ${msg}`);
  process.exit(1);
}

/** Extract content of a TOML section (up to the next section header). */
function getTomlSection(content: string, section: string): string {
  const re = new RegExp(`^\\[${section.replace(/\./g, "\\.")}\\]`, "m");
  const match = re.exec(content);
  if (!match) return "";
  const after = content.slice(match.index + match[0].length);
  const nextSection = after.search(/^\[[a-zA-Z]/m);
  return nextSection >= 0 ? after.slice(0, nextSection) : after;
}

function parseDependenciesFromToml(content: string): string[] {
  const section = getTomlSection(content, "project");
  const match = section.match(/dependencies\s*=\s*\[([\s\S]*?)\]/);
  if (!match) return [];
  const deps: string[] = [];
  for (const m of match[1].matchAll(/"([^"]+)"|'([^']+)'/g)) {
    deps.push(m[1] ?? m[2]);
  }
  return deps;
}

function parseEntryFromToml(content: string): string {
  const section = getTomlSection(content, "tool.pymode");
  const match = section.match(/main\s*=\s*["']([^"']+)["']/);
  return match ? match[1] : "";
}

function findEntryPoint(projectDir: string): string {
  // Check pyproject.toml for [tool.pymode] main
  const pyproject = path.join(projectDir, "pyproject.toml");
  if (fs.existsSync(pyproject) && fs.statSync(pyproject).isFile()) {
    try {
      const content = fs.readFileSync(pyproject, "utf-8");
      const entry = parseEntryFromToml(content);
      if (entry) return entry;
    } catch {
      // ignore
    }
  }

  // Fallback: check common entry points
  const candidates = ["src/entry.py", "entry.py", "app.py", "main.py", "worker.py"];
  for (const candidate of candidates) {
    if (fs.existsSync(path.join(projectDir, candidate))) {
      return candidate;
    }
  }

  error(
    "No entry point found. Create src/entry.py or specify one: " +
      `npx tsx ${process.argv[1]} <project-dir> <entry.py>`
  );
}

function collectPyFiles(projectDir: string): string[] {
  const EXCLUDE = new Set(["__pycache__", ".venv", "node_modules"]);
  const pyFiles: string[] = [];

  function walk(dir: string): void {
    const entries = fs.readdirSync(dir, { withFileTypes: true });
    for (const entry of entries) {
      if (entry.isDirectory()) {
        if (!EXCLUDE.has(entry.name)) {
          walk(path.join(dir, entry.name));
        }
      } else if (entry.isFile() && entry.name.endsWith(".py")) {
        pyFiles.push(path.join(dir, entry.name));
      }
    }
  }

  walk(projectDir);
  return pyFiles.sort();
}

function main(): void {
  const projectDir = path.resolve(process.argv[2] ?? ".");
  let entryPoint = process.argv[3] ?? "";

  if (!fs.existsSync(projectDir) || !fs.statSync(projectDir).isDirectory()) {
    error(`Project directory not found: ${projectDir}`);
  }

  if (!entryPoint) {
    entryPoint = findEntryPoint(projectDir);
  }

  const entryFile = path.join(projectDir, entryPoint);
  if (!fs.existsSync(entryFile) || !fs.statSync(entryFile).isFile()) {
    error(`Entry point not found: ${entryFile}`);
  }

  // Convert entry point path to Python module name
  const entryModule = entryPoint.replace(/\.py$/, "").replaceAll("/", ".");

  info(`Project:     ${projectDir}`);
  info(`Entry point: ${entryPoint}`);
  info(`Module:      ${entryModule}`);

  const pyFiles = collectPyFiles(projectDir);
  if (pyFiles.length === 0) {
    error(`No .py files found in ${projectDir}`);
  }

  info(`Found ${pyFiles.length} Python files`);

  // Generate user-files.ts
  const output = path.join(WORKER_DIR, "src", "user-files.ts");
  const lines: string[] = [];
  lines.push("// Auto-generated by scripts/bundle-project.ts — do not edit.");
  lines.push("// User project files mounted at /app/ in the VFS.\n");
  lines.push(`export const entryModule = ${JSON.stringify(entryModule)};\n`);
  lines.push("export const userFiles: Record<string, string> = {");

  for (const filepath of pyFiles) {
    const relPath = path.relative(projectDir, filepath);
    const content = fs.readFileSync(filepath, "utf-8");
    lines.push(`  "app/${relPath}": ${JSON.stringify(content)},`);
  }

  lines.push("};\n");
  fs.writeFileSync(output, lines.join("\n"));

  info(`Generated ${output}`);
  info(`  Entry module: ${entryModule}`);
  info(`  Files bundled: ${pyFiles.length}`);

  // Check for pyproject.toml dependencies
  const pyproject = path.join(projectDir, "pyproject.toml");
  if (fs.existsSync(pyproject) && fs.statSync(pyproject).isFile()) {
    try {
      const content = fs.readFileSync(pyproject, "utf-8");
      const deps = parseDependenciesFromToml(content);
      if (deps.length > 0) {
        warn(`Dependencies found: ${deps.join(", ")}`);
        warn("Run: npx tsx scripts/bundle-packages.ts to bundle them into site-packages.zip");
      }
    } catch {
      // ignore
    }
  }

  console.log();
  info("Done. Deploy with: cd worker && npx wrangler deploy");
}

main();
