#!/bin/bash
# Generate a TypeScript module containing stdlib .py files as string constants
# for embedding in the CF Workers MemFS.
#
# Output: worker/src/stdlib-fs.ts

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
ROOT_DIR="$(dirname "$SCRIPT_DIR")"
STDLIB_SRC="$ROOT_DIR/cpython/Lib"
OUTPUT="$ROOT_DIR/worker/src/stdlib-fs.ts"

if [ ! -d "$STDLIB_SRC" ]; then
    echo "Error: CPython stdlib not found at $STDLIB_SRC"
    echo "Run build-phase2.sh first."
    exit 1
fi

# Modules Python needs to boot (from PYTHONVERBOSE trace)
# Frozen modules are already in the binary, but encodings + site helpers
# must come from the filesystem.
BOOT_FILES=(
    # encodings — required before Python can decode any text
    "encodings/__init__.py"
    "encodings/aliases.py"
    "encodings/utf_8.py"
    "encodings/ascii.py"
    "encodings/latin_1.py"
    # boot chain: traceback support
    "linecache.py"
    "tokenize.py"
    "token.py"
    # json
    "json/__init__.py"
    "json/decoder.py"
    "json/encoder.py"
    "json/scanner.py"
    # re (regex)
    "re/__init__.py"
    "re/_casefix.py"
    "re/_compiler.py"
    "re/_constants.py"
    "re/_parser.py"
    # collections & functools
    "collections/__init__.py"
    "collections/abc.py"
    "functools.py"
    "operator.py"
    # core types
    "enum.py"
    "types.py"
    "typing.py"
    "warnings.py"
    "contextlib.py"
    "dataclasses.py"
    "copy.py"
    "copyreg.py"
    # text
    "string.py"
    "textwrap.py"
    # data
    "base64.py"
    "hashlib.py"
    "hmac.py"
    "secrets.py"
    # numbers
    "random.py"
    "bisect.py"
    "heapq.py"
    "numbers.py"
    "fractions.py"
    "decimal.py"
    # datetime
    "datetime.py"
    "calendar.py"
    # path
    "fnmatch.py"
    "glob.py"
    # url
    "urllib/__init__.py"
    "urllib/parse.py"
    # misc
    "keyword.py"
    "reprlib.py"
    "traceback.py"
    "struct.py"
)

PYMODE_LIB="$ROOT_DIR/lib"

# PyMode runtime modules bundled alongside stdlib
PYMODE_FILES=(
    "pymode/__init__.py"
    "pymode/http.py"
    "pymode/tcp.py"
    "pymode/importer.py"
)

echo "Generating $OUTPUT..."

cat > "$OUTPUT" << 'HEADER'
// Auto-generated by scripts/generate-stdlib-fs.sh
// Contains Python stdlib files and PyMode runtime for the CF Workers MemFS.
// Keys are paths relative to the stdlib root (e.g. "encodings/__init__.py").

export const stdlibFS: Record<string, string> = {
HEADER

COUNT=0
for relpath in "${BOOT_FILES[@]}"; do
    srcfile="$STDLIB_SRC/$relpath"
    if [ ! -f "$srcfile" ]; then
        echo "  Warning: $relpath not found, skipping"
        continue
    fi

    # Escape backticks and backslashes for template literal
    echo -n "  \"$relpath\": \`" >> "$OUTPUT"
    sed 's/\\/\\\\/g; s/`/\\`/g; s/\${/\\${/g' "$srcfile" >> "$OUTPUT"
    echo "\`," >> "$OUTPUT"

    COUNT=$((COUNT + 1))
done

# Bundle PyMode runtime modules
for relpath in "${PYMODE_FILES[@]}"; do
    srcfile="$PYMODE_LIB/$relpath"
    if [ ! -f "$srcfile" ]; then
        echo "  Warning: pymode/$relpath not found, skipping"
        continue
    fi

    echo -n "  \"$relpath\": \`" >> "$OUTPUT"
    sed 's/\\/\\\\/g; s/`/\\`/g; s/\${/\\${/g' "$srcfile" >> "$OUTPUT"
    echo "\`," >> "$OUTPUT"

    COUNT=$((COUNT + 1))
done

echo "};" >> "$OUTPUT"

# Report size
SIZE=$(wc -c < "$OUTPUT" | tr -d ' ')
SIZE_KB=$((SIZE / 1024))
echo "Done: $OUTPUT ($COUNT files, ${SIZE_KB}KB)"
